---
- name: Docker | Install docker to CentOS
  block:
    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

- import_tasks: CentOS.yaml
  when: ansible_facts['distribution'] == 'CentOS'

- import_tasks: Ubuntu.yaml
  when: ansible_distribution == "Ubuntu"

- name: Docker | Install pip
  block:
    - name: Docker | remove python3-pip
      apt:
        name: python3-pip
        state: absent

    - name: Docker | Get pip
      get_url:
        url: "{{ pip_url }}"
        dest: "{{ lookup('env', 'HOME') }}/get-pip.py"

    - name: Docker | Install pip
      ansible.builtin.script: "{{ lookup('env', 'HOME') }}/get-pip.py"
      args:
        executable: python3
      register: pkg

    - debug:
        msg: "{{ pkg.stdout_lines }}"

  when: ansible_distribution == "Ubuntu"

- name: Docker | Install required python docker modules
  pip:
    name: 
      - jsondiff
      - docker-compose
    state: present

- name: Docker | Log into private registry
  docker_login:
    registry: "{{ docker_registry.url }}"
    username: "{{ docker_registry.user }}"
    password: "{{ docker_registry.password }}"
  when: docker_registry_login == true

#- name: Docker | Add current user to Docker group
#  user:
#    name: "{{ ansible_ssh_user }}"
#    groups: docker
#
#- name: Docker | Add crontab prune job
#  cron:
#    name: "Docker prune"
#    hour: "0"
#    job: "docker system prune -f"
#  when: docker_prune_job
