     - name: Delete | Uninstall ols version of Docker
       apt:
         name:
           - docker
           - docker-engine
           - docker.io
           - containerd
           - runc
         state: absent

     - name: Install required system packages
       apt:
         update_cache: yes
         name:
           - ca-certificates
           - curl
           - gnupg
           - lsb-release
    
     - name: Add Docker GPG apt Key
       apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present
     
     - name: Add Docker Repository
       apt_repository:
         repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
         state: present
         update_cache: yes
   
     - name: Install docker and docker compose v2
       apt: 
         name: 
           - docker-ce
           - docker-ce-cli
           - containerd.io
           - docker-buildx-plugin
           - docker-compose-plugin
         state: latest

     - name: Ensure service is started and enabled at boot
       service:
         name: docker
         state: started
         enabled: yes
